name: CI/CD Workflow demo-nodejs
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+' # Matches Semver-like tags such as 1.0.0
    paths:
      - 'apps/demo-nodejs/**'
      - '.github/workflows/cicd_nodejs.yaml'

jobs:
  build:
    uses: ./.github/workflows/template_build_push.yaml
    with:
      context: ./demo-nodejs
      dockerfile: ./demo-nodejs/Dockerfile
      image_name: demo-nodejs
    secrets:
      DOCKER_REGISTRY_URI: ${{ secrets.DOCKER_REGISTRY_URI }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  #deploy_to_eks:
  #  needs: build
  #  uses: ./.github/workflows/template_gitops.yaml
  #  with:
  #    environment: prod
  #    image_tag: ${{ needs.build.outputs.image_tag }}
  #    values_file_path: clusters/prod/apps/webapp-color.values.yaml
  #    app_name: webapp-color
  #    env_repo: josefloressv/kcd_colombia_env
  #  secrets:
  #    ENV_REPO_PAT: ${{ secrets.ENV_REPO_PAT }}