name: Workflow CI/CD demo-nodejs
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+' # Matches Semver-like tags such as 1.0.0
    paths:
      - 'demo-nodejs/app/**'
permissions:
  id-token: write
  contents: write
  pull-requests: write
  

jobs:
  build:
    uses: ./.github/workflows/template_build_push.yaml
    with:
      context: ./demo-nodejs
      dockerfile: ./demo-nodejs/Dockerfile
      image_name: demo-nodejs
    secrets:
      DOCKER_REGISTRY_URI: ${{ secrets.DOCKER_REGISTRY_URI }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      

  deploy_to_k8s:
    needs: build
    uses: ./.github/workflows/template_gitops.yaml
    with:
      environment: prod
      image_tag: ${{ needs.build.outputs.image_tag_private }}
      values_file_path: demo-nodejs/prod/values.yaml
      app_name: demo-nodejs
      env_repo: mateotorres2409/demos-env
    secrets:
      ENV_REPO_PAT: ${{ secrets.ENV_REPO_PAT }}