name: Pull Request Workflow demo-nodejs
on:
  pull_request:
    branches:
        - main
    paths:
      - 'demo-nodejs/**'
      - '.github/workflows/pr_nodejs.yaml'

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: |
          # Run pytest to exercise the Flask test client
          echo "Running tests..."